jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.vmImage }}

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'
      - script: |
          node --version
          npm --version
        displayName: 'Print node + npm versions'
      - task: Npm@1
        inputs:
          command: install
        displayName: 'Install deps with npm'
      - task: Npm@1
        inputs:
          command: custom
          customCommand: test
        displayName: 'Run tests'
